# Generate latest build and push it to dockerhub on push to develop branch.
# NOTE: This workflow does not include any tests, nor any dependencies, since bors guarantees
# that only code that passes all tests is ever pushed to develop.
name: push to dockerhub
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  push:
    branches:
      - develop
    tags:
      - '*'

jobs:
  dockerpush:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      if: env.DOCKER_USERNAME != null
      uses: actions/checkout@v2
    - name: push to dockerhub
      if: env.DOCKER_USERNAME != null
      run: make dockerpush
